# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bang_app', '0005_auto_20170223_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='expiration_date',
            field=models.CharField(max_length=10),
        ),
    ]
